tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"

brew "bash-completion"
brew "coreutils"
brew "findutils", args: ["with-default-names"]
brew "git"
brew "git-crypt"
brew "go"
brew "jq"
brew "kubectx"
brew "kubernetes-cli"
brew "mpv"
brew "mtr"
brew "pstree"
brew "reattach-to-user-namespace"
brew "terraform"
brew "the_silver_searcher"
brew "vim"
brew "watch"
brew "wget"
brew "xz"

cask "caskroom/versions/docker-edge"
cask "borgbackup"
cask "skype"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "viscosity"

cask "caskroom/fonts/font-hack-nerd-font"
cask "caskroom/fonts/font-inconsolata"
cask "caskroom/fonts/font-inconsolata-nerd-font"
cask "caskroom/fonts/font-inconsolata-nerd-font-mono"
