# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "monsenso/macos-10.13"
  config.vm.box_version = "1.0.0"
  #config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision :shell, privileged: false,
    inline: "curl -L https://raw.githubusercontent.com/claytono/dotfiles/master/.bootstrap/bootstrap.sh | bash"
end
