#!/bin/bash

set -e -o pipefail

command_exists () {
  type "$1" &> /dev/null ;
}

if ! command_exists curl; then
  NEED="curl $NEED"
fi

if ! command_exists git; then
  NEED="git $NEED"
fi

if [[ "$NEED" != "" ]]; then
if command_exists apt-get; then
  sudo apt-get update
  sudo apt-get install $NEED build-essential -y
else
  echo "Need the following binaries available: $NEED"
  exit 1
fi
fi

curl -fLo /tmp/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm
chmod a+x /tmp/yadm

if [[ $(id -u -n) == "vagrant" ]]; then
  /tmp/yadm clone /vagrant --bootstrap
else
  /tmp/yadm clone https://github.com/claytono/dotfiles
fi

rm -f /tmp/yadm
