---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3  # v31
      with:
        github_access_token: ${{ github.token }}

    - name: Setup Cachix
      uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c  # v17
      with:
        name: claytono
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Cache pre-commit
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5
      with:
        path: ~/.cache/pre-commit
        key: precommit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          precommit-

    - name: Run lint
      run: nix develop --command ./scripts/lint --from-ref origin/${{ github.base_ref || 'main' }}
        --to-ref HEAD
